from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = ROOT / "results"
SUMMARY = RESULTS_DIR / "summary.md"


def stamp() -> str:
    return datetime.now().strftime("%H:%M:%S")


def log(message: str) -> None:
    print(f"[{stamp()}] {message}")


def section(title: str) -> None:
    print()
    print(f"== {title} ==")


def run_cmd(cmd: list[str], *, cwd: Path | None = None, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        env=env,
        capture_output=True,
        text=True,
    )


def line_for_output(output: str) -> str:
    for line in output.splitlines():
        line = line.strip()
        if line.startswith("1. ") or "retrieved_response:" in line or "Validation Status:" in line:
            return line
    lines = [line.strip() for line in output.splitlines() if line.strip()]
    return lines[-1] if lines else "no output"


def require_env_path(name: str) -> Path:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(
            f"Missing required environment variable {name}. Set it before using --with-superoptix."
        )
    return Path(value).expanduser().resolve()


def run_standalone(label: str, script_name: str) -> tuple[bool, str]:
    log(f"Running {label} via demo/{script_name}")
    proc = run_cmd([sys.executable, str(ROOT / "demo" / script_name)])
    output = (proc.stdout or "") + (proc.stderr or "")
    detail = line_for_output(output)
    log(f"{label}: {'PASS' if proc.returncode == 0 else 'FAIL'}")
    print(detail)
    return proc.returncode == 0, detail


def run_superoptix(label: str, agent_name: str, framework: str) -> tuple[bool, str]:
    superoptix_root = require_env_path("SUPEROPTIX_ROOT")
    turboagents_root = require_env_path("TURBOAGENTS_ROOT")
    validation_root = require_env_path("SUPEROPTIX_VALIDATION_ROOT")
    env = os.environ.copy()
    env["PYTHONPATH"] = f"{superoptix_root}:{turboagents_root}"
    python = superoptix_root / ".venv" / "bin" / "python"
    log(f"Running {label} using {agent_name} ({framework})")
    proc = run_cmd(
        [
            str(python),
            "-m",
            "superoptix.cli.main",
            "agent",
            "run",
            agent_name,
            "--framework",
            framework,
            "--goal",
            "What is NEON-FOX-742?",
        ],
        cwd=validation_root,
        env=env,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    detail = line_for_output(output)
    log(f"{label}: {'PASS' if proc.returncode == 0 else 'FAIL'}")
    print(detail)
    return proc.returncode == 0, detail


def write_summary(results: list[tuple[str, bool, str]]) -> None:
    lines = [
        "# TurboAgents Demo Summary",
        "",
        "This summary is generated by `scripts/run_demo.py`.",
        "",
    ]
    for name, ok, detail in results:
        lines.append(f"- {name}: {'passed' if ok else 'failed'}")
        lines.append(f"  - {detail}")
    SUMMARY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Wrote summary to {SUMMARY}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--with-superoptix", action="store_true")
    args = parser.parse_args()

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    section("TurboAgents Demo")
    log("Starting standalone demo validation")

    results: list[tuple[str, bool, str]] = []

    for name, script in [
        ("Standalone LanceDB", "standalone_lancedb_demo.py"),
        ("Standalone SurrealDB", "standalone_surrealdb_demo.py"),
    ]:
        ok, detail = run_standalone(name, script)
        results.append((name, ok, detail))
        print()

    if args.with_superoptix:
        section("SuperOptiX Integrations")
        log("Starting framework integration validation")
        for name, agent, framework in [
            ("SuperOptiX DSPy", "rag_surrealdb_dspy_demo", "dspy"),
            ("SuperOptiX Pydantic AI", "rag_surrealdb_pydanticai_demo", "pydantic-ai"),
            ("SuperOptiX OpenAI Agents SDK", "rag_surrealdb_openai_demo", "openai"),
        ]:
            ok, detail = run_superoptix(name, agent, framework)
            results.append((name, ok, detail))
            print()

    write_summary(results)


if __name__ == "__main__":
    main()
